environment:
  nodejs_version: "7"
cache:
 - "%LOCALAPPDATA%\\Yarn"

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn
  - yarn run prepare
  - git submodule sync
  - git submodule update --init --recursive --remote
test_script:
  - ./node_modules/.bin/jest -i
  - ./node_modules/.bin/flow check
  - ./node_modules/.bin/standard
  - yarn run clean

build: off
